-- WarlockDemonology.lua
-- july 2025 by Smufrik

-- MoP: Use UnitClass instead of UnitClassBase

local _, playerClass = UnitClass('player')
if playerClass ~= 'WARLOCK' then 
    -- Not a warlock, exiting WarlockDemonology.lua
    return 
end
-- Warlock detected, continuing WarlockDemonology.lua loading

local addon, ns = ...
local Hekili = _G[ addon ]
local class, state = Hekili.Class, Hekili.State

local floor = math.floor
local strformat = string.format

local spec = Hekili:NewSpecialization(266, true)

spec.name = "Demonology"
spec.role = "DAMAGER"
spec.primaryStat = 7 -- Intellect

-- Use MoP power type numbers instead of Enum
-- Mana = 0, SoulShards = 7 in MoP Classic
spec:RegisterResource( 0, { -- Mana = 0 in MoP
    -- Life Tap mana restoration (Warlock signature mechanic)
    life_tap = {
        last = function ()
            return state.last_cast_time.life_tap or 0
        end,
        interval = 1.5, -- Life Tap GCD
        value = function()
            -- Life Tap converts health to mana (30% max mana in MoP)
            return state.last_ability == "life_tap" and state.mana.max * 0.30 or 0
        end,
    },
    
    -- Harvest Life mana return (Demonology talent)
    harvest_life = {
        aura = "harvest_life",
        last = function ()
            local app = state.buff.harvest_life.applied
            local t = state.query_time
            return app + floor( ( t - app ) / 1 ) * 1
        end,
        interval = 1,
        value = function()
            -- Harvest Life channels mana return over time
            return state.buff.harvest_life.up and state.mana.max * 0.03 or 0 -- 3% per second
        end,
    },
    
    -- Dark Pact mana return (from demon health)
    dark_pact = {
        last = function ()
            return state.last_cast_time.dark_pact or 0
        end,
        interval = 1.5, -- Dark Pact GCD
        value = function()
            -- Dark Pact converts demon health to mana
            return state.last_ability == "dark_pact" and state.mana.max * 0.25 or 0
        end,
    },
}, {
    -- Base mana regeneration for Demonology
    base_regen = function ()
        local base = state.mana.max * 0.01 -- 1% base (Warlocks have low base regen)
        local spirit_bonus = (state.stat.spirit or 0) * 0.4 -- Spirit is less effective for Warlocks
        
        -- Fel Armor bonus to mana regeneration
        if state.buff.fel_armor.up then
            base = base * 1.20 -- 20% bonus
        end
        
        return (base + spirit_bonus) / 5 -- Convert to per-second
    end,
    
    -- Improved Life Tap talent bonus
    improved_life_tap = function ()
        return state.talent.improved_life_tap.enabled and 0.2 or 0 -- 20% spell power as mana efficiency
    end,
} )

-- Soul Shards resource registration
spec:RegisterResource( 7, { -- Soul Shards = 7 in MoP
    -- Soul Burn shard conversion
    soul_burn = {
        last = function ()
            return state.last_cast_time.soul_burn or 0
        end,
        interval = 1,
        value = function()
            -- Soul Burn converts shard for enhanced abilities
            return state.last_ability == "soul_burn" and -1 or 0 -- Consumes 1 shard
        end,
    },
    
    -- Shadowburn shard generation
    shadowburn_shard = {
        last = function ()
            return state.last_cast_time.shadowburn or 0
        end,
        interval = 1,
        value = function()
            -- Shadowburn generates shard if target dies within 5 seconds
            if state.last_ability == "shadowburn" and state.target.time_to_die < 5 then
                return 1 -- Generates 1 shard
            end
            return 0
        end,
    },
}, {
    -- Base soul shard mechanics
    base_generation = function ()
        -- Soul shards don't regenerate naturally, must be generated by abilities
        return 0
    end,
    
    -- Soul Link talent affects shard efficiency
    soul_link_efficiency = function ()
        return state.talent.soul_link.enabled and 0.05 or 0 -- 5% efficiency bonus
    end,
} )

-- Demonic Fury resource system (Demonology signature mechanic)
spec:RegisterResource( 15, { -- Demonic Fury = 15 in MoP
    -- Demonic Fury generation from Shadow Bolt
    shadow_bolt_generation = {
        last = function ()
            return state.last_cast_time.shadow_bolt or 0
        end,
        interval = 1,
        value = function()
            -- Shadow Bolt generates 40 Demonic Fury
            return state.last_ability == "shadow_bolt" and 40 or 0
        end,
    },
    
    -- Demonic Fury generation from Soul Fire
    soul_fire_generation = {
        last = function ()
            return state.last_cast_time.soul_fire or 0
        end,
        interval = 1,
        value = function()
            -- Soul Fire generates 25 Demonic Fury
            return state.last_ability == "soul_fire" and 25 or 0
        end,
    },
    
    -- Demonic Fury generation from Life Tap
    life_tap_generation = {
        last = function ()
            return state.last_cast_time.life_tap or 0
        end,
        interval = 1,
        value = function()
            -- Life Tap generates 50 Demonic Fury
            return state.last_ability == "life_tap" and 50 or 0
        end,
    },
    
    -- Demonic Fury generation from Hand of Gul'dan
    hand_of_guldan_generation = {
        last = function ()
            return state.last_cast_time.hand_of_guldan or 0
        end,
        interval = 1,
        value = function()
            -- Hand of Gul'dan generates 60 Demonic Fury
            return state.last_ability == "hand_of_guldan" and 60 or 0
        end,
    },
    
    -- Demonic Fury consumption for Metamorphosis
    metamorphosis_consumption = {
        last = function ()
            return state.last_cast_time.metamorphosis or 0
        end,
        interval = 1,
        value = function()
            -- Metamorphosis consumes 1000 Demonic Fury
            return state.last_ability == "metamorphosis" and -1000 or 0
        end,
    },
    
    -- Demonic Fury consumption for Hand of Gul'dan (Metamorphosis)
    meta_hand_consumption = {
        last = function ()
            return state.last_cast_time.meta_hand_of_guldan or 0
        end,
        interval = 1,
        value = function()
            -- Hand of Gul'dan in Metamorphosis consumes 200 Demonic Fury
            return state.last_ability == "meta_hand_of_guldan" and -200 or 0
        end,
    },
    
    -- Demonic Fury consumption for Touch of Chaos
    touch_of_chaos_consumption = {
        last = function ()
            return state.last_cast_time.touch_of_chaos or 0
        end,
        interval = 1,
        value = function()
            -- Touch of Chaos consumes 100 Demonic Fury
            return state.last_ability == "touch_of_chaos" and -100 or 0
        end,
    },
}, {
    -- Demonic Fury generation modifiers
    demonic_calling_bonus = function ()
        return state.talent.demonic_calling.enabled and 0.15 or 0 -- 15% bonus from Demonic Calling
    end,
    
    demonic_embrace_bonus = function ()
        return state.talent.demonic_embrace.enabled and 0.1 or 0 -- 10% bonus from Demonic Embrace
    end,
    
    demonic_presence_bonus = function ()
        return state.buff.demonic_presence.up and 0.2 or 0 -- 20% bonus from Demonic Presence
    end,
} )


-- Pet management system for Demonology Warlock
local function summon_demon(demon_type)
    -- Track which demon is active
    if demon_type == "imp" then
        applyBuff("grimoire_of_sacrifice_imp")
    elseif demon_type == "voidwalker" then
        applyBuff("grimoire_of_sacrifice_voidwalker")
    elseif demon_type == "succubus" then
        applyBuff("grimoire_of_sacrifice_succubus")
    elseif demon_type == "felhunter" then
        applyBuff("grimoire_of_sacrifice_felhunter")
    elseif demon_type == "felguard" then
        applyBuff("grimoire_of_sacrifice_felguard")
    end
end

-- Pet stat tracking for Demonology
local function update_pet_stats()
    local pet_health = UnitHealth("pet") or 0
    local pet_max_health = UnitHealthMax("pet") or 1
    local pet_health_pct = pet_health / pet_max_health
    
    -- Update pet health state for Dark Pact calculations
    if state then
        state.pet_health_pct = pet_health_pct
    end
end

-- Add reset_precast hook for state management and form checking
spec:RegisterHook( "reset_precast", function()
    -- Set safe default values to avoid errors
    local metamorphosis_up = false
    local current_mana = -1
    local current_shards = -1
    
    -- Safely access resource values using the correct state access pattern
    if state.mana then
        current_mana = state.mana.current or -1
    end
    if state.soul_shards then
        current_shards = state.soul_shards.current or -1
    end
    
    -- Fallback to direct API calls if state resources are not available
    if current_mana == -1 then
        current_mana = UnitPower("player", 0) or 0 -- Mana = power type 0
    end
    if current_shards == -1 then
        current_shards = UnitPower("player", 7) or 0 -- Soul Shards = power type 7 in MoP
    end
    
    -- Check for Metamorphosis buff
    local meta_name = GetSpellInfo(103958) -- Metamorphosis spell ID in MoP
    if meta_name and UnitBuff("player", meta_name) then
        applyBuff("metamorphosis")
        metamorphosis_up = true
    else
        removeBuff("metamorphosis")
    end
    
    -- Check which demon is active
    local active_pet = UnitCreatureFamily("pet")
    if active_pet then
        if active_pet == "Imp" then
            applyBuff("grimoire_of_sacrifice_imp")
        elseif active_pet == "Voidwalker" then
            applyBuff("grimoire_of_sacrifice_voidwalker")
        elseif active_pet == "Succubus" then
            applyBuff("grimoire_of_sacrifice_succubus")
        elseif active_pet == "Felhunter" then
            applyBuff("grimoire_of_sacrifice_felhunter")
        elseif active_pet == "Felguard" then
            applyBuff("grimoire_of_sacrifice_felguard")
        end
    end
end )

-- Additional debugging hook for when recommendations are generated
spec:RegisterHook( "runHandler", function( ability )
    -- Only log critical issues
    if not ability then
        -- Nil ability passed to runHandler
        return
    end
end )

-- Debug hook to check state at the beginning of each update cycle
spec:RegisterHook( "reset", function()
    -- Minimal essential verification
    if not state or not state.spec or state.spec.id ~= 266 then
        return
    end
    
    -- Basic state verification - level check
    if level and level < 10 then
        return
    end
end )

-- Talents - MoP compatible talent structure
-- Using tier/column system instead of retail IDs
spec:RegisterTalents( {
    -- Tier 1 (Level 15) - Movement/Utility
    dark_regeneration    = { 1, 1, 108359 }, -- Tier 1, Column 1, SpellID
    soul_leech           = { 1, 2, 108370 }, -- Tier 1, Column 2, SpellID
    harvest_life         = { 1, 3, 108371 }, -- Tier 1, Column 3, SpellID

    -- Tier 2 (Level 30) - Crowd Control
    howl_of_terror       = { 2, 1, 5484 },   -- Tier 2, Column 1, SpellID
    mortal_coil          = { 2, 2, 6789 },   -- Tier 2, Column 2, SpellID
    shadowfury           = { 2, 3, 30283 },  -- Tier 2, Column 3, SpellID

    -- Tier 3 (Level 45) - Defensive
    soul_link            = { 3, 1, 108415 }, -- Tier 3, Column 1, SpellID
    sacrificial_pact     = { 3, 2, 108416 }, -- Tier 3, Column 2, SpellID
    dark_bargain         = { 3, 3, 110913 }, -- Tier 3, Column 3, SpellID

    -- Tier 4 (Level 60) - Utility
    blood_fear           = { 4, 1, 111397 }, -- Tier 4, Column 1, SpellID
    burning_rush         = { 4, 2, 111400 }, -- Tier 4, Column 2, SpellID
    unbound_will         = { 4, 3, 108482 }, -- Tier 4, Column 3, SpellID

    -- Tier 5 (Level 75) - Demons
    grimoire_of_supremacy = { 5, 1, 108499 }, -- Tier 5, Column 1, SpellID
    grimoire_of_service   = { 5, 2, 108501 }, -- Tier 5, Column 2, SpellID
    grimoire_of_sacrifice = { 5, 3, 108503 }, -- Tier 5, Column 3, SpellID

    -- Tier 6 (Level 90) - DPS Enhancement
    archimondes_vengeance = { 6, 1, 130736 }, -- Tier 6, Column 1, SpellID
    kiljadens_cunning     = { 6, 2, 137587 }, -- Tier 6, Column 2, SpellID
    mannoroth_fury        = { 6, 3, 137288 }, -- Tier 6, Column 3, SpellID
} )

-- Glyphs (Enhanced System - authentic MoP 5.4.8 glyph system)
spec:RegisterGlyphs( {
    -- Major glyphs - Demonology Combat
    [58616] = "soul_swap",            -- Soul Swap now has a 50% chance to not trigger a cooldown
    [58617] = "haunt",                -- Haunt now has a 50% chance to not trigger a cooldown
    [58618] = "unstable_affliction",  -- Unstable Affliction now has a 50% chance to not trigger a cooldown
    [58619] = "corruption",           -- Corruption now has a 50% chance to not trigger a cooldown
    [58620] = "agony",                -- Agony now has a 50% chance to not trigger a cooldown
    [58621] = "siphon_life",          -- Siphon Life now has a 50% chance to not trigger a cooldown
    [58622] = "drain_life",           -- Drain Life now has a 50% chance to not trigger a cooldown
    [58623] = "drain_soul",           -- Drain Soul now has a 50% chance to not trigger a cooldown
    [58624] = "fear",                 -- Fear now has a 50% chance to not trigger a cooldown
    [58625] = "howl_of_terror",       -- Howl of Terror now has a 50% chance to not trigger a cooldown
    [58626] = "death_coil",           -- Death Coil now has a 50% chance to not trigger a cooldown
    [58627] = "shadow_bolt",          -- Shadow Bolt now has a 50% chance to not trigger a cooldown
    [58628] = "incinerate",           -- Incinerate now has a 50% chance to not trigger a cooldown
    [58629] = "immolate",             -- Immolate now has a 50% chance to not trigger a cooldown
    [58630] = "conflagrate",          -- Conflagrate now has a 50% chance to not trigger a cooldown
    [58631] = "chaos_bolt",           -- Chaos Bolt now has a 50% chance to not trigger a cooldown
    [58632] = "shadowburn",           -- Shadowburn now has a 50% chance to not trigger a cooldown
    [58633] = "fel_flame",            -- Fel Flame now has a 50% chance to not trigger a cooldown
    [58634] = "soul_fire",            -- Soul Fire now has a 50% chance to not trigger a cooldown
    [58635] = "metamorphosis",        -- Metamorphosis now has a 50% chance to not trigger a cooldown
    [58636] = "hand_of_guldan",       -- Hand of Gul'dan now has a 50% chance to not trigger a cooldown
    [58637] = "demonbolt",            -- Demonbolt now has a 50% chance to not trigger a cooldown
    [58638] = "doom",                 -- Doom now has a 50% chance to not trigger a cooldown
    [58639] = "shadowflame",          -- Shadowflame now has a 50% chance to not trigger a cooldown
    [58640] = "dancing_rune_weapon",  -- Dancing Rune Weapon lasts 5 sec longer but generates 20% less runic power
    [58641] = "vampiric_aura",        -- Your Vampiric Aura affects 2 additional party members but the healing is reduced by 25%
    [58642] = "unholy_frenzy",        -- Your Unholy Frenzy grants an additional 10% attack speed but lasts 50% shorter
    [58643] = "corpse_explosion",     -- Your corpses explode when they expire, dealing damage to nearby enemies
    [58644] = "disease",              -- Your diseases last 50% longer but deal 25% less damage
    [58645] = "resilient_grip",       -- Your Death Grip removes one movement impairing effect from yourself
    [58646] = "shifting_presences",   -- Reduces the rune cost to change presences by 1, but you cannot change presences while in combat
    
    -- Minor glyphs - Cosmetic and convenience
    [58647] = "corpse_walker",        -- Your undead minions appear to be spectral
    [58648] = "the_geist",            -- Your ghoul appears as a geist
    [58649] = "deaths_embrace",       -- Your death grip has enhanced visual effects
    [58650] = "bone_spikes",          -- Your abilities create bone spike visual effects
    [58651] = "unholy_vigor",         -- Your character emanates an unholy aura
    [58652] = "the_bloodied",         -- Your weapons appear to be constantly dripping blood
    [58653] = "runic_mastery",        -- Your runes glow with enhanced energy when available
    [58654] = "the_forsaken",         -- Your character appears more skeletal and undead
    [58655] = "shadow_walk",          -- Your movement leaves shadowy footprints
    [58656] = "deaths_door",          -- Your abilities create portal-like visual effects
} )

-- Ticks gained on refresh (MoP version for Warlock Demonology).
local tick_calculator = setfenv( function( t, action, pmult )
    local state = _G["Hekili"] and _G["Hekili"].State or {}
    local remaining_ticks = 0
    local potential_ticks = 0
    local remains = t.remains
    local tick_time = t.tick_time
    local ttd = min( state.fight_remains or 300, state.target and state.target.time_to_die or 300 )

    local aura = action
    -- Handle specific warlock spell mappings
    if action == "hand_of_guldan" then aura = "shadowflame" end
    if action == "metamorphosis_doom" then aura = "doom" end

    local class = _G["Hekili"] and _G["Hekili"].Class or {}
    local duration = class.auras and class.auras[ aura ] and class.auras[ aura ].duration or 0
    local app_duration = min( ttd, duration )
    local app_ticks = app_duration / tick_time

    remaining_ticks = min( remains, ttd ) / tick_time
    duration = max( 0, min( remains + duration, 1.3 * duration, ttd ) )
    potential_ticks = min( duration, ttd ) / tick_time

    -- Metamorphosis adjustments - certain spells have different durations in meta form
    if buff.metamorphosis and buff.metamorphosis.up then
        if action == "corruption" then aura = "doom" end
    end

    return max( 0, potential_ticks - remaining_ticks )
end, {} )

-- Auras
spec:RegisterAuras( {
    -- Core Metamorphosis and resources
    metamorphosis = {
        id = 103958,
        duration = 30,
        max_stack = 1,
    },
    dark_soul_knowledge = {
        id = 113861,
        duration = 20,
        max_stack = 1,
    },
    molten_core = {
        id = 122355,
        duration = 14,
        max_stack = 5,
    },
    decimation = {
        id = 108869,
        duration = 10,
        max_stack = 1,
    },
    demonic_fury = {
        id = 109145,
        duration = 3600,
        max_stack = 1000,
    },
    
    -- DoTs and debuffs
    corruption = {
        id = 146739,
        duration = 14,
        tick_time = 2,
        max_stack = 1,
    },
    doom = {
        id = 603,
        duration = 60,
        tick_time = 15,
        max_stack = 1,
    },
    immolate = {
        id = 348,
        duration = 15,
        tick_time = 3,
        max_stack = 1,
    },
    shadowflame = {
        id = 47960,
        duration = 8,
        tick_time = 2,
        max_stack = 1,
    },
    curse_of_elements = {
        id = 1490,
        duration = 300,
        max_stack = 1,
    },
    curse_of_enfeeblement = {
        id = 109466,
        duration = 30,
        max_stack = 1,
    },
    curse_of_exhaustion = {
        id = 18223,
        duration = 30,
        max_stack = 1,
    },
    
    -- Crowd control
    fear = {
        id = 5782,
        duration = 20,
        mechanic = "fear",
        max_stack = 1,
    },
    howl_of_terror = {
        id = 5484,
        duration = 8,
        mechanic = "fear",
        max_stack = 1,
    },
    mortal_coil = {
        id = 6789,
        duration = 3,
        mechanic = "horror",
        max_stack = 1,
    },
    banish = {
        id = 710,
        duration = 30,
        mechanic = "banish",
        max_stack = 1,
    },
    shadowfury = {
        id = 30283,
        duration = 3,
        mechanic = "stun",
        max_stack = 1,
    },
    
    -- Grimoire talents
    grimoire_of_sacrifice = {
        id = 108503,
        duration = 3600,
        max_stack = 1,
    },
    grimoire_of_sacrifice_imp = {
        id = 0, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1,
    },
    grimoire_of_sacrifice_voidwalker = {
        id = 0, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1,
    },
    grimoire_of_sacrifice_succubus = {
        id = 0, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1,
    },
    grimoire_of_sacrifice_felhunter = {
        id = 0, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1,
    },
    grimoire_of_sacrifice_felguard = {
        id = 0, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1,
    },
    
    -- Self buffs and defensives
    unending_resolve = {
        id = 104773,
        duration = 8,
        max_stack = 1,
    },
    soul_link = {
        id = 108446,
        duration = 3600,
        max_stack = 1,
    },
    dark_bargain = {
        id = 110913,
        duration = 8,
        max_stack = 1,
    },
    burning_rush = {
        id = 111400,
        duration = 3600,
        max_stack = 1,
    },
    twilight_ward = {
        id = 6229,
        duration = 30,
        max_stack = 1,
    },
    blood_horror = {
        id = 111397,
        duration = 60,
        max_stack = 1,
    },
    
    -- Procs and effects
    demonic_rebirth = {
        id = 88448,
        duration = 15,
        max_stack = 1,
    },
    backdraft = {
        id = 117828,
        duration = 15,
        max_stack = 3,
    },
    hand_of_guldan = {
        id = 86040,
        duration = 0,
        max_stack = 1,
    },
    
    -- Pet abilities
    commanding_presence = {
        id = 0, -- Custom ID for tracking 
        duration = 3600,
        max_stack = 1,
    },
    demonic_synergy = {
        id = 0, -- Custom ID for tracking
        duration = 10,
        max_stack = 1,
    },
    fel_intelligence = {
        id = 54424,
        duration = 3600,
        max_stack = 1,
    },
    
    -- Utilities
    life_tap = {
        id = 1454,
        duration = 40,
        max_stack = 1,
    },
    drain_life = {
        id = 689,
        duration = 3,
        tick_time = 1,
        max_stack = 1,
    },
    drain_soul = {
        id = 1120,
        duration = 6,
        tick_time = 1,
        max_stack = 1,
    },
    soulburn = {
        id = 74434,
        duration = 30,
        max_stack = 1,
    },
    health_funnel = {
        id = 755,
        duration = 6,
        tick_time = 1,
        max_stack = 1,
    },
    
    -- Metamorphosis abilities
    carrion_swarm = {
        id = 103967,
        duration = 0,
        max_stack = 1,
    },
    chaos_wave = {
        id = 124916,
        duration = 0,
        max_stack = 1,
    },
    touch_of_chaos = {
        id = 103964, 
        duration = 0,
        max_stack = 1,
    },
    void_ray = {
        id = 115422,
        duration = 0,
        max_stack = 1,
    },
    
    -- MoP Tier Sets
    -- Tier 14 (MoP - Heart of Fear)
    tier14_2pc = {
        id = 123136, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1
    },
    tier14_4pc = {
        id = 123141, -- Custom ID for tracking
        duration = 30,
        max_stack = 1
    },

    -- Tier 15 (MoP - Throne of Thunder)
    tier15_2pc = {
        id = 138129, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1
    },
    tier15_4pc = {
        id = 138134, -- Custom ID for tracking
        duration = 15,
        max_stack = 1
    },

    -- Tier 16 (MoP - Siege of Orgrimmar)
    tier16_2pc = {
        id = 145091, -- Custom ID for tracking
        duration = 3600,
        max_stack = 1
    },
    tier16_4pc = {
        id = 145164, -- Custom ID for tracking
        duration = 30,
        max_stack = 1
    },
} )





-- Tweaking for new Demonology APL.
local doom_applied = false

spec:RegisterEvent( "PLAYER_REGEN_ENABLED", function ()
    doom_applied = false
end )

-- Event handler to ensure Demonology spec is enabled  
spec:RegisterEvent( "PLAYER_ENTERING_WORLD", function ()
    if state.spec.id == 266 then
        -- Ensure the spec is enabled in the profile
        if Hekili.DB and Hekili.DB.profile and Hekili.DB.profile.specs then
            if not Hekili.DB.profile.specs[266] then
                Hekili.DB.profile.specs[266] = {}
            end
            Hekili.DB.profile.specs[266].enabled = true
            
            -- Set default package if none exists
            if not Hekili.DB.profile.specs[266].package then
                Hekili.DB.profile.specs[266].package = "Demonology"
            end
        end
    end
end )

--[[spec:RegisterStateExpr( "opener_done", function ()
    return doom_applied
end )--]]

-- Metamorphosis and pet management for MoP

spec:RegisterStateFunction( "enter_metamorphosis", function ()
    applyBuff( "metamorphosis" )
    -- In MoP, Metamorphosis transforms some spells
    if buff.metamorphosis.up then
        -- Corruption becomes Doom in Metamorphosis
        if debuff.corruption.up then
            removeBuff( "corruption" )
            applyDebuff( "target", "doom" )
        end
    end
end )

spec:RegisterStateFunction( "exit_metamorphosis", function ()
    removeBuff( "metamorphosis" )
    -- Transform back doom to corruption if needed
    if debuff.doom.up and not action.doom.lastCast then
        removeBuff( "doom" )
        applyDebuff( "target", "corruption" )
    end
end )

-- Function to summon and manage demons
spec:RegisterStateFunction( "summon_demon", function( demon_type )
    -- Remove existing demon buffs
    removeBuff( "grimoire_of_sacrifice_imp" )
    removeBuff( "grimoire_of_sacrifice_voidwalker" )
    removeBuff( "grimoire_of_sacrifice_succubus" )
    removeBuff( "grimoire_of_sacrifice_felhunter" )
    removeBuff( "grimoire_of_sacrifice_felguard" )
    
    -- Apply new demon buff
    if demon_type then
        applyBuff( "grimoire_of_sacrifice_" .. demon_type )
    end
end )

local soul_shard_generators = {
    shadow_bolt       = true,
    soul_fire         = true,
    fel_flame         = true,
    drain_soul        = true
}

local soul_shard_spenders = {
    summon_imp        = true,
    summon_voidwalker = true,
    summon_succubus   = true,
    summon_felhunter  = true,
    summon_felguard   = true,
    soul_burn         = true,
    hand_of_guldan    = true
}

spec:RegisterHook( "runHandler", function( ability )
    local a = class.abilities[ ability ]

    if not a then return end
    
    -- Handle Soul Shard generation
    if soul_shard_generators[ ability ] then
        if not buff.metamorphosis.up then
            -- Chance to generate soul shard based on MoP mechanics
            if math.random() < 0.15 then -- 15% base chance
                gain( 1, "soul_shards" )
            end
        end
    end
    
    -- Handle Demonic Fury generation in Metamorphosis
    if buff.metamorphosis.up and a.startsCombat then
        if ability == "touch_of_chaos" then
            gain( 40, "demonic_fury" )
        elseif ability == "carrion_swarm" then
            gain( 25, "demonic_fury" )
        elseif ability == "chaos_wave" then
            gain( 350, "demonic_fury" )
        end
    end
end )

spec:RegisterHook( "gain", function( amt, resource, overflow )
    if overflow == nil then overflow = true end
    if amt > 0 and resource == "soul_shards" then
        -- Soul shard generation can trigger various effects
    end
end )

spec:RegisterStateTable( "warlock", setmetatable( {},{
    __index = function( t, k )
        if k == "no_cds" then return not toggle.cooldowns
        elseif k == "metamorphosis_active" then return buff.metamorphosis.up
        elseif k == "in_metamorphosis" then return buff.metamorphosis.up
        elseif k == "pet_active" then 
            return buff.grimoire_of_sacrifice_imp.up or 
                   buff.grimoire_of_sacrifice_voidwalker.up or
                   buff.grimoire_of_sacrifice_succubus.up or
                   buff.grimoire_of_sacrifice_felhunter.up or
                   buff.grimoire_of_sacrifice_felguard.up
        elseif debuff[ k ] ~= nil then return debuff[ k ]
        end
    end
} ) )

-- MoP: Check for active DoTs
spec:RegisterStateExpr( "dots_ticking", function ()
    return debuff.corruption.up or debuff.doom.up or debuff.immolate.up or debuff.shadowflame.up
end )

-- Essential state expressions for APL functionality
spec:RegisterStateExpr( "time_to_die", function ()
    return target.time_to_die or 300
end )

spec:RegisterStateExpr( "spell_targets", function ()
    return active_enemies or 1
end )

spec:RegisterStateExpr( "mana_deficit", function ()
    return mana.max - mana.current
end )

spec:RegisterStateExpr( "mana_time_to_max", function ()
    return mana.deficit / mana.regen
end )

spec:RegisterStateExpr( "soul_shards_deficit", function ()
    return soul_shards.max - soul_shards.current
end )

spec:RegisterStateExpr( "time_to_pool", function ()
    local mana_deficit = mana.max - mana.current
    if mana_deficit <= 0 then return 0 end
    return mana_deficit / mana.regen
end )

-- State expression to check if we can make recommendations
spec:RegisterStateExpr( "can_recommend", function ()
    return state.spec and state.spec.id == 266 and level >= 10
end )

-- Essential state expressions for APL functionality
spec:RegisterStateExpr( "current_mana", function ()
    return mana.current or 0
end )

spec:RegisterStateExpr( "current_soul_shards", function ()
    return soul_shards.current or 0
end )

spec:RegisterStateExpr( "max_mana", function ()
    return mana.max or 100000
end )

spec:RegisterStateExpr( "mana_regen", function ()
    return mana.regen or 500
end )

spec:RegisterStateExpr( "in_combat", function ()
    return combat > 0
end )

spec:RegisterStateExpr( "player_level", function ()
    return level or 85
end )

-- Additional essential state expressions for APL compatibility
spec:RegisterStateExpr( "metamorphosis_form", function ()
    return buff.metamorphosis.up
end )

spec:RegisterStateExpr( "health_pct", function ()
    return health.percent or 100
end )

spec:RegisterStateExpr( "target_health_pct", function ()
    return target.health.percent or 100
end )

-- Demonic Fury tracking for Metamorphosis
spec:RegisterStateExpr( "demonic_fury_current", function ()
    return buff.demonic_fury.stack or 0
end )

spec:RegisterStateExpr( "demonic_fury_deficit", function ()
    return 1000 - ( buff.demonic_fury.stack or 0 )
end )

-- Pet type checking
spec:RegisterStateExpr( "imp_active", function ()
    return buff.grimoire_of_sacrifice_imp.up
end )

spec:RegisterStateExpr( "felguard_active", function ()
    return buff.grimoire_of_sacrifice_felguard.up
end )

spec:RegisterStateExpr( "voidwalker_active", function ()
    return buff.grimoire_of_sacrifice_voidwalker.up
end )

spec:RegisterStateExpr( "succubus_active", function ()
    return buff.grimoire_of_sacrifice_succubus.up
end )

spec:RegisterStateExpr( "felhunter_active", function ()
    return buff.grimoire_of_sacrifice_felhunter.up
end )

-- MoP Tier Sets for Warlock Demonology

-- Tier 14 (MoP - Heart of Fear)
spec:RegisterGear( "tier14", 84430, 84429, 84428, 84427, 84426 )
-- 2-piece: When your corruption deals damage, you have a 2% chance to gain 20% additional haste for 20 sec.
spec:RegisterAura( "t14_2pc_proc", {
    id = 123136,
    duration = 20,
    max_stack = 1
} )
-- 4-piece: Your Curse spells and Shadowflame have a 40% chance to reduce the cast time of your next Malefic Grasp by 100%.
spec:RegisterAura( "t14_4pc_proc", {
    id = 123141,
    duration = 30,
    max_stack = 1
} )

-- Tier 15 (MoP - Throne of Thunder)
spec:RegisterGear( "tier15", 95430, 95429, 95428, 95427, 95426 )
-- 2-piece: When you use Dark Soul, you also gain 15% spell haste for 20 sec.
spec:RegisterAura( "t15_2pc_proc", {
    id = 138129,
    duration = 20,
    max_stack = 1
} )
-- 4-piece: When your Corruption deals damage, you have a 30% chance to deal Shadowflame damage to all enemies within 8 yards of your target.
spec:RegisterAura( "t15_4pc_proc", {
    id = 138134,
    duration = 15,
    max_stack = 1
} )

-- Tier 16 (MoP - Siege of Orgrimmar)
spec:RegisterGear( "tier16", 99159, 99158, 99157, 99156, 99155 )
-- 2-piece: Metamorphosis now reduces damage taken by an additional 20%, and you regenerate Demonic Fury 20% faster.
spec:RegisterAura( "t16_2pc", {
    id = 145091,
    duration = 3600,
    max_stack = 1
} )
-- 4-piece: While in Metamorphosis, your Touch of Chaos and Soul Fire deal 25% additional damage as Chaos damage.
spec:RegisterAura( "t16_4pc_proc", {
    id = 145164,
    duration = 30,
    max_stack = 1
} )

-- MoP: Demonic Fury calculation for Metamorphosis
local function calculate_demonic_fury_generation( ability )
    local base_generation = 0
    
    if ability == "shadow_bolt" then
        base_generation = 40
    elseif ability == "soul_fire" then
        base_generation = 60
    elseif ability == "hand_of_guldan" then
        base_generation = 400
    elseif ability == "life_tap" then
        base_generation = 50
    end
    
    -- Apply modifiers for gear sets
    local modifier = 1
    if set_bonus.tier16_2pc > 0 then
        modifier = modifier * 1.2 -- 20% faster Demonic Fury regeneration
    end
    
    return base_generation * modifier
end

-- Soul Shard generation tracking for MoP
spec:RegisterStateFunction( "generate_soul_shard", function()
    if not buff.metamorphosis.up then
        -- Base 15% chance to generate soul shard on damaging spells
        if math.random() < 0.15 then
            gain( 1, "soul_shards" )
        end
    end
end )

-- Abilities specific to MoP Demonology
spec:RegisterAbilities( {
    -- Shadow Bolt: Primary nuke, generates soul shards and demonic fury
    shadow_bolt = {
        id = 686,
        cast = 2.5,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 0.02,
        spendType = "mana",
        startsCombat = true,
        velocity = 20,
        handler = function()
            generate_soul_shard()
            if buff.metamorphosis.up then
                gain( calculate_demonic_fury_generation("shadow_bolt"), "demonic_fury" )
            end
        end,
    },

    -- Soul Fire: High damage nuke, enhanced in metamorphosis
    soul_fire = {
        id = 6353,
        cast = function() 
            if buff.decimation.up then return 0 end
            return 4.0 * haste 
        end,
        cooldown = 0,
        gcd = "spell",
        school = "fire",
        spend = 0.08,
        spendType = "mana",
        startsCombat = true,
        velocity = 20,
        handler = function()
            if buff.decimation.up then
                removeBuff("decimation")
            end
            generate_soul_shard()
            if buff.metamorphosis.up then
                gain( calculate_demonic_fury_generation("soul_fire"), "demonic_fury" )
            end
        end,
    },

    -- Touch of Chaos: Metamorphosis replacement for Shadow Bolt
    touch_of_chaos = {
        id = 103964,
        cast = 2.5,
        cooldown = 0,
        gcd = "spell",
        school = "chaos",
        spend = 40,
        spendType = "demonic_fury",
        startsCombat = true,
        form = "metamorphosis",
        velocity = 20,
        handler = function()
            -- Touch of Chaos doesn't generate soul shards but uses demonic fury
        end,
    },

    -- Metamorphosis: Transform into demon form
    metamorphosis = {
        id = 103958,
        cast = 0,
        cooldown = 600,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        toggle = "cooldowns",
        handler = function()
            applyBuff("metamorphosis")
            applyBuff("demonic_fury")
            enter_metamorphosis()
        end,
    },

    -- Hand of Gul'dan: Soul shard spender, applies shadowflame
    hand_of_guldan = {
        id = 71521,
        cast = 2.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = true,
        velocity = 15,
        handler = function()
            applyDebuff("target", "shadowflame")
            if buff.metamorphosis.up then
                gain( calculate_demonic_fury_generation("hand_of_guldan"), "demonic_fury" )
            end
        end,
    },

    -- Carrion Swarm: Metamorphosis AoE ability
    carrion_swarm = {
        id = 103967,
        cast = 0,
        cooldown = 8,
        gcd = "spell",
        school = "shadow",
        spend = 50,
        spendType = "demonic_fury",
        startsCombat = true,
        form = "metamorphosis",
        handler = function()
            -- AoE damage handled by game
        end,
    },

    -- Chaos Wave: High demonic fury cost AoE
    chaos_wave = {
        id = 124916,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "chaos",
        spend = 350,
        spendType = "demonic_fury",
        startsCombat = true,
        form = "metamorphosis",
        handler = function()
            -- High AoE damage
        end,
    },

    -- Dark Soul: Knowledge - Major DPS cooldown
    dark_soul_knowledge = {
        id = 113861,
        cast = 0,
        cooldown = 120,
        gcd = "off",
        school = "shadow",
        startsCombat = false,
        toggle = "cooldowns",
        handler = function()
            applyBuff("dark_soul_knowledge")
            if set_bonus.tier15_2pc > 0 then
                applyBuff("t15_2pc_proc")
            end
        end,
    },

    -- Life Tap: Convert health to mana, generates demonic fury in meta
    life_tap = {
        id = 1454,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        startsCombat = false,
        handler = function()
            applyBuff("life_tap")
            if buff.metamorphosis.up then
                gain( calculate_demonic_fury_generation("life_tap"), "demonic_fury" )
            end
        end,
    },

    -- Summon abilities using soul shards
    summon_imp = {
        id = 688,
        cast = 6.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        essential = true,
        handler = function()
            summon_demon("imp")
        end,
    },

    summon_felguard = {
        id = 30146,
        cast = 6.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        essential = true,
        handler = function()
            summon_demon("felguard")
        end,
    },

    summon_voidwalker = {
        id = 697,
        cast = 6.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        essential = true,
        handler = function()
            summon_demon("voidwalker")
        end,
    },

    summon_succubus = {
        id = 712,
        cast = 6.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        essential = true,
        handler = function()
            summon_demon("succubus")
        end,
    },

    summon_felhunter = {
        id = 691,
        cast = 6.0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        essential = true,
        handler = function()
            summon_demon("felhunter")
        end,
    },

    -- Fel Flame: Instant cast spell, weak but mobile
    fel_flame = {
        id = 77799,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "fire",
        spend = 0.04,
        spendType = "mana",
        startsCombat = true,
        velocity = 25,
        handler = function()
            generate_soul_shard()
        end,
    },

    -- Void Ray: Metamorphosis channeled ability
    void_ray = {
        id = 115422,
        cast = 0,
        channeled = true,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 100,
        spendType = "demonic_fury",
        startsCombat = true,
        form = "metamorphosis",
        handler = function()
            -- Channeled damage
        end,
    },

    -- Soulburn: Enhances next spell
    soulburn = {
        id = 74434,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 1,
        spendType = "soul_shards",
        startsCombat = false,
        handler = function()
            applyBuff("soulburn")
        end,
    },

    -- Drain Soul: Channel to finish low health enemies
    drain_soul = {
        id = 1120,
        cast = 6,
        channeled = true,
        cooldown = 0,
        gcd = "spell",
        school = "shadow",
        spend = 0.06,
        spendType = "mana",
        startsCombat = true,
        handler = function()
            applyDebuff("target", "drain_soul")
            -- Guaranteed soul shard if target dies during channel
        end,
    },
} )

spec:RegisterRanges( "shadow_bolt", "corruption", "fear", "curse_of_elements" )

spec:RegisterOptions( {
    enabled = true,

    aoe = 3,
    cycle = false,

    nameplates = true,
    nameplateRange = 40,
    rangeFilter = false,

    damage = true,
    damageDots = true,
    damageExpiration = 3,

    potion = "jade_serpent_potion",

    package = "Demonology"
} )

spec:RegisterSetting( "metamorphosis_save", false, {
    name = strformat( "Save %s for Burn Phase", Hekili:GetSpellLinkWithTexture( spec.abilities.metamorphosis.id ) ),
    desc = strformat( "If checked, %s will only be recommended during burn phases or when dark soul is active.",
        Hekili:GetSpellLinkWithTexture( spec.abilities.metamorphosis.id ) ),
    type = "toggle",
    width = "full",
} )

spec:RegisterSetting( "corruption_refresh", 30, {
    name = strformat( "%s Refresh Percentage", Hekili:GetSpellLinkWithTexture( spec.auras.corruption.id ) ),
    desc = strformat( "Percentage of remaining duration at which to refresh %s.",
        Hekili:GetSpellLinkWithTexture( spec.auras.corruption.id ) ),
    type = "range",
    min = 10,
    max = 90,
    step = 5,
    width = 1.5
} )

spec:RegisterVariable( "metamorphosis_save", function()
    return state.settings.metamorphosis_save ~= false
end )

spec:RegisterVariable( "corruption_refresh", function()
    return state.settings.corruption_refresh or 30
end )

spec:RegisterStateExpr( "should_refresh_corruption", function()
    local refresh_pct = state.settings.corruption_refresh or 30
    return debuff.corruption.remains_percent <= refresh_pct
end )

spec:RegisterStateExpr( "demonic_fury", function()
    return demonic_fury.current
end )

spec:RegisterStateExpr( "demonic_fury_deficit", function()
    return demonic_fury.max - demonic_fury.current
end )

spec:RegisterStateExpr( "current_demonic_fury", function()
    return demonic_fury.current or 0
end )

spec:RegisterStateExpr( "metamorphosis_active", function()
    return buff.metamorphosis.up and 1 or 0
end )

spec:RegisterStateExpr( "demonic_presence_bonus", function()
    return buff.demonic_presence.up and 0.2 or 0 -- 20% damage bonus
end )

spec:RegisterStateExpr( "dark_soul_bonus", function()
    return buff.dark_soul.up and 0.3 or 0 -- 30% damage bonus
end )

spec:RegisterStateExpr( "molten_core_bonus", function()
    return buff.molten_core.up and 0.15 or 0 -- 15% damage bonus
end )

spec:RegisterStateExpr( "soulburn_active", function()
    return buff.soulburn.up and 1 or 0
end )

spec:RegisterStateExpr( "spell_power", function()
    return GetSpellBonusDamage(6) -- Shadow school
end )

spec:RegisterStateExpr( "metamorphosis_ready", function()
    return demonic_fury.current >= 1000 and 1 or 0
end )


spec:RegisterPack( "Demonology", 20250713, [[Hekili:fRvBpUTns4FllcGZDOP6K9(AdwBGMlnxtqBqq9EOFZs0s0RfwjrFsuzVfyH(TFZqkkjsrkPTnhkcsIT0WzgoCMN5f6Dl3D3UTXeoD3Nx5V6s)RxEUN)YlUy1QDB5pDIUB7js0dK7HpKtYG)990mwolLD)tCAjhF9tPmsmYMswvreqYUT7Rss5FmF3EdEVYB15(xC(5aTNOrWJV6QDBpMehtL0slJ2T9UJjL1H4Fj1HnsVoKDa(EepHLxhMMuYHxFGvuh(Z0hsst82Tv8qHAWdYOCc8Xpl2D0CY(uA8U3jfqrYjKlWoHDxDygjhyFgnNdIey9VIRClqeNwKaFkMX9IzSmVc6HcA5rKv72kve8TSSDCyFyiNU1FwDyll4jrpKKF)WLF(yQ5xksYifpjvnWgSh2U8N6ycNvfDmGDii6iHvIS7IXy3wGzWEnIKhrtH)NLhNGVPSVwxEKvLghijsynZyfNoYktk7eS13YH)ac8aPkLp5jWDfj5pqbTPQuCg)yc)yDyPudlFkpcoQz3NeP894s6x2xvBEwasEWJj5XShRd3SUo8g)E2i1ch9SYjRUYVoCbARyPWZY9uSdCkYij5GR4M6Wv(gQ5QbYF10h2mPhojpUoSGeLqsvh5juTJO9vho4ftkEiac7s9Qovh(8Z1H0)lnQItdoDKusdq5)1E(RNeS3MpshJzGQKrsdA5Da8DWTvY)bITJ57PfL0cHhoiGl))GaszS4GdvfpHc4Qz4L)EGp1HBbg14Jnh9Ox8P6nO8UEm59XmW(V9rsrwNZ8rkCq2iKHNCimAseeILMcYuC(bUyaXuPp3sPphGF0em6ikmj7uqjkyuhVzC8ow29vKIyvGwsoNcs)Eb4NAVpQhgQHKI7PCpurd4SG4eQkgPtNkRYGDxqSsGOQ9dJPA)ypGDWVNvXf(dA4b9rQucQOkpq(5aCP91EPRFanNMbron6O0fJWObhHiSGVssRAn3(YuibYyyGguRx670nwyE0ou0CwhOA9yUkdfkatasTuh)PKHG9c0Um2xXZwamUrsbnp5DD86aaLFivS0oTrGMFQGgXY2tMgp)3jfPSOhEle41wLGr0e6ZLZBXHpbWTYYma5l9vm9Ias0vjte0rrZ4KuqEE3djrzjfumpzjbE9HKiQNAfTI0kzTOzgOO6QWv9POd4W0yI(vtzg)cMs8hz)KdKFWG4PSwEMi8Wlk5ScRvLOhYH8hQclnT0iqBaqPT4LRVStMI3bwS7byksUTCCD8cR3Y7ueiMBRdVOfJB80wPjhaWgYjBh1TvJWkkQA2BrpfLIlarQkfU96f01rB)Y6e6IjSXTyLe2kCSecliXos2PrUSUn3NNwdYBWAfoVGnlNvW4hlfj)g62MabkPeboaPQGyl74Ce3zZxIhb)MdqGYKjg)ml)7ZugG5GUnJnUGevcu8fdZazXIyMBCMQYKgfhAZL(2TwJMh8Na0XcvL(I2BeUnjqVp7bxsankrVwcB1gy1pgvPl60iZI2hMOttV(qsAkTOh08rcuiCWEwkxcRvoDYHbLF0a3mSWJot(OW2spL5u(VT6rgfCuGa3gSATEPbOKZgw2n4OfwO34HInAnES0VpkywgIgl8hTbxowhWZdM0kK7CWa75G2VRBPTLe)vSDY42o(g3hFepz3iF)z6QDCuUFw0VgoII)vv6RHKGM(4IurgU5TNQ65p9G(4bQbqMcPoHTaIE0(E3mwox34B60QYlkz6klWx3IyP(JjRrbX(nQCqq6hZFtlcyC0kz)EFaWnuhd)kauHDJ9pz4Z6IJJ0IGZeufaU1GouKWGx0aMFDFWeStrfA(iLVltP0XsigIGB5fs7IC)Jm)CPbWT0V0P0hfeBRaKUo8DaJHSjtaHdr)qxK5GpAjoco0mLDIHoVI8qVUPNLxdTNr)pvGcao8LmSBvsfNLr44dax3CW11R(t)sso8QLqRa)78YQtiNqcKshyhIf)6w6wnt6o3jD6tbRBfx4Cf2c0X1v)jl7(MjA9Y29x5ExP6pOtrV2jXTD43r8noj2mvx3Aw62i327hsTy3FGLMYEu0eow)eMcKIHovL4cXbLYrYuCq23((kUIUCMW0vLRrDCmsCmHt2dr4VfS1HFp(9gJH676JgP5P6L4y)uQTt1x250iEPDTSohN1UowNJdO1IBE9l17XQHa6y7BLjqvYXC2)6jkMtyRcuFo2RUYn6O(YrIA06ayo2vvz6ZlO0b7DhAoK9)GtAhGk1Cm5723Rdp)VKO45eFw(nlW0nm3OOCgEYU9l1QJ(BVZPJJx3UMUswnLBQRiYr8sDSc3(QdJHhZnvv)spQh5y2c1Ja)(xDiqxfCyaWhZuA4L6caDWXXQYGAYGcqFvDOTbNw)PxbV5lQuA1FsYIsV2SCF36)rVeu2jOlL0BuZADTQfthRiNCc6ucAPMtGUeSsJ1uxVj5W6z13UvwkhQ6i7YMkeewL3llhd(sD4CVeXwwdmeo9dG60ZEdoR81QRZtSbgopHnRVXFYfVY5IVYFHZloCZkFXwcoNh9I)6lEPHcf3GlO55NT1cv)f3DhDidCDdyp)8W7(PptAVhUxmte7vxxoxFz0USXerd)M6Y36Z32IP7mGdUjUf4LBTz9s)fNzD(AsPoNRtRVKntzz9eCXWRxd9GAe5l7AY6lCJBks66cvjIkH0lrnQqqCp)S(e)rtH)KCRPbX2T1GPPondW1E2KlUTBL3iVfR1lvWcBHVHZX)oHrSo8Zq2Emo6dW)B)mtBgKDGpLChhyNnhaUfobrKH6ZC4IgQJQ8funSnOqDQ1kGXXsw4CUIBw636LR)JKXukQQEqrmYvRiz2lDkGgstZPafO9OtDn0sHt9wQTx3OSZEMEgsuVakuwZFqFBw77DZK8Z(882SE1I(ZX72R8vhI2NiNHCuLXHsqnGQBVaWaTNtrIK)cM0Mz0LQ0oH8Sm7RnRV2FS1yF(AluQ(M1N7VWoFVuzxSnHmtr2vtPlug5T1iWycrRQLOM2FAz95UWRdt1bamQWhZFQzJr)zM)WYu4lw)bJzJt6dntp78WFGy24WF0WRx1CZw)gJtK50(Bx9DQyQY)EhoP(1M2PcqgQ5GjktBo(vDBY0HbCMPdV(sZ18hj4r)AKn5ypOvTRZE9YXHAxq0sNF76B6b(oL90yQgoZLVyIRe10I2m5d387SPyOylODzYZq3TxlXekVgiQS4l37ghsyITJHiAXJM11)AQoZkROHxXM1x0iYpya6j5z)lhylPIFKvSB7VaDOcbb0CXTfS7)9]])